### ISSUE TITLE
Typo on js.js and scss.js

### ISSUE THREAD

**Issue by danbovey** [JakeCobley/Kettle#54]
https://github.com/JakeCobley/Kettle/blob/master/gulp-tasks/scss.js#L13

https://github.com/JakeCobley/Kettle/blob/master/gulp-tasks/js.js#L12
https://github.com/JakeCobley/Kettle/blob/master/gulp-tasks/js.js#L11

**Comment by JakeCobley** [comment]
I didn't spot that. Will fix shortly.

Thanks,
