### ISSUE TITLE
JS task ordering issue with sourcemaps and uglify

### ISSUE THREAD

**Issue by danbovey** [JakeCobley/Kettle#55]
If the user gets config to choose when to use sourcemaps and uglify, it will break as uglify() needs to come before sourcemaps.write()

https://github.com/JakeCobley/Kettle/blob/master/gulp-tasks/js.js#L13

**Comment by JakeCobley** [comment]
I didn't catch this since its not technically a bug with the current setup. However you are quite right since I intend to add in more configs this will need sorting. 

I will update shortly, Thanks

**Comment by JakeCobley** [comment]
Closing issue. Removed sourcemaps from the JS task since currently there is not functionally for JS files to be combined.
